### Get all profiles
GET http://localhost:3000/Profile

### Create New Profile
POST http://localhost:3000/Profile
Content-Type: application/json

{
    "username": "Chalida",
    "password": "1234",
    "mobile": "0916985133",
    "cardId": "1219900093638"
}

### Search profile by UUID
GET http://localhost:3000/Profile/uuidSearch

### Get some profile by Profile/:id
GET http://localhost:3000/Profile/2ca710fb-b8e8-4386-ad1f-789f070e7056

### Login
POST http://localhost:3000/Login
Content-Type: application/json

{
    "username": "Chalida",
    "password": "U2FsdGVkX1/5azmD1ag6zkYlKIWModzBTNZCiqefHF8="
}

### New encode by Crypto on 14-09-2025
POST http://localhost:3000/Profile/encode

### New decode by Crypto on 14-09-2025
POST http://localhost:3000/Profile/decode