### Get all profiles
GET http://localhost:3000/Profile

### Create New Profile
POST http://localhost:3000/Profile
Content-Type: application/json

{
    "username": "Chalida",
    "password": "1234",
    "mobile": "0916985133",
    "cardId": "1219900093638"
}

### Search profile by UUID
GET http://localhost:3000/Profile/uuidSearch

### Get some profile by Profile/:id
GET http://localhost:3000/Profile/a0652305-3519-4dfc-86a8-f3de40aea65b

### Login
POST http://localhost:3000/Login
Content-Type: application/json

{
    "username": "Chalida",
    "password": "U2FsdGVkX18yi/4ROU3Jo3so99J28/MVJjIxrA/wXdg="
}

### New encode by Crypto on 14-09-2025
POST http://localhost:3000/encode

### New decode by Crypto on 14-09-2025
POST http://localhost:3000/decode

### Create New Encode with New encode by Crypto on 14-09-2025
POST http://localhost:3000/encode
Content-Type: application/json

{
    "username": "Eakkapob",
    "password": "123456",
    "mobile": "0916985132",
    "cardId": "1219900093637"
}

### Create New Decode with New encode by Crypto on 14-09-2025 (For POST)
POST http://localhost:3000/decode
Content-Type: application/json

{
    "encryptedPassword": "kXVggANr63nWcwlXaM6n5A==",
    "encryptedCardID": "ILRsRo0bRIIOmuA3mlW/9g=="
}

### Create New Decode with New encode by Crypto on 14-09-2025 (For GET)
GET http://localhost:3000/decode/775e35b9-524d-4eda-aa03-63704bb8e0c2